config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  root to: "pages#home"

  resources :dashboard_form, except: %i[index]
  get '/dashboard_forms', to: 'dashboard_forms#index', as: :form_for_admin

  devise_for :admins
    resources :dashboard_forms
  devise_for :users, controllers: { registrations: "users/registrations" }
    resources :information_forms


  get "about", to: "pages#about", as: :about
  get "information_form", to: "information_form#index", as: :form_for_user
  get 'users' => 'users#primary', as: :user_root
  get 'admins' => 'admin#primary', as: :admin_root


end

app/controllers/information_forms_controller.rb
class InformationFormsController < ApplicationController
  before_action :set_information_form, only: %i[ show edit update destroy ]

  # GET /information_forms or /information_forms.json
  def index
    @information_forms = InformationForm.all
  end


  # GET /information_forms/1 or /information_forms/1.json
  def show

  end

  def key_info
    @fuel_needed = fuel_needed.all
  end

  # GET /information_forms/new
  def new
    @information_form = InformationForm.new
  end

  # GET /information_forms/1/edit
  def edit
  end

  # POST /information_forms or /information_forms.json
  def create
    @information_form = InformationForm.new(information_form_params)

    respond_to do |format|
      if @information_form.save
        format.html { redirect_to information_form_url(@information_form), notice: "Information form was successfully created." }
        format.json { render :show, status: :created, location: @information_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @information_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /information_forms/1 or /information_forms/1.json
  def update
    respond_to do |format|
      if @information_form.update(information_form_params)
        format.html { redirect_to information_form_url(@information_form), notice: "Information form was successfully updated." }
        format.json { render :show, status: :ok, location: @information_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @information_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information_forms/1 or /information_forms/1.json
  def destroy
    @information_form.destroy

    respond_to do |format|
      format.html { redirect_to information_forms_url, notice: "Information form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information_form
      @information_form = InformationForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def information_form_params
      params.require(:information_form).permit(:name, :address, :email_address, :fuel_capacity, :current_fuel_content, :fuel_needed, :instructions_for_delivery, :is_admin)
    end
end

app/views/information_forms/_form.html.erb
<%= simple_form_for(@information_form) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :email_address %>
    <%= f.input :fuel_capacity %>
    <%= f.input :current_fuel_content %>
    <%= f.input :fuel_needed %>
    <%= f.input :instructions_for_delivery %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/information_forms/_information_form.html.erb
<div id="<%= dom_id information_form %>">
  <p>
    <strong>Name:</strong>
    <%= information_form.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= information_form.address %>
  </p>

  <p>
    <strong>Email Address:</strong>
    <%= information_form.email_address %>
  </p>

  <p>
    <strong>Fuel Capacityin litres:</strong>
    <%= information_form.fuel_capacity %>
  </p>

  <p>
    <strong>Current Fuel Content in litres:</strong>
    <%= information_form.current_fuel_content %>
  </p>

  <p>
    <strong>Fuel Needed in litres:</strong>
    <%= information_forms.fuel_needed %>
  </p>

  <p>
    <strong>Instructions for Delivery:</strong>
    <%= information_form.instructions_for_delivery %>
  </p>

</div>

app/views/information_forms/edit.html.erb
<h1>Editing information form</h1>

<%= render "form", information_form: @information_form %>

<br>

<div>
  <%= link_to "Show this information form", @information_form %> |
  <%= link_to "Back to information forms", information_forms_path %>
</div>

app/views/information_forms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Information forms</h1>

<div id="information_forms">
  <% @information_forms.each do |information_form| %>
    <%= render information_form %>
    <p>
      <%= link_to "Show this information form", information_forms %>
    </p>
  <% end %>
</div>

<%= link_to "New information form", new_information_form_path %>
<%= link_to "Back to User Main Page", user_registration_url, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>

app/views/information_forms/new.html.erb
<div style="background_color: blue">
  <h1>New information form</h1>

  <%= render "form", information_form: @information_form %>

  <br>

  <div>
    <%= link_to "Back to information forms", information_forms_path %>
  </div>
</div>

app/views/information_forms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @information_form %>

<div>
  <%= link_to "Edit this information form", edit_information_form_path(@information_form) %>
  <%= link_to "Back to information forms", information_forms_path %>

  <%= button_to "Destroy this information form", @information_form, method: :delete %>
</div>