config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  root to: "pages#home"

  resources :dashboard_form, except: %i[index]
  get '/dashboard_forms', to: 'dashboard_forms#index', as: :form_for_admin

  devise_for :admins
    resources :dashboard_forms
  devise_for :users, controllers: { registrations: "users/registrations" }
    resources :information_forms


  get "about", to: "pages#about", as: :about
  get "information_form", to: "information_form#index", as: :form_for_user
  get 'users' => 'users#primary', as: :user_root
  get 'admins' => 'admin#primary', as: :admin_root


end

app/views/pages/about.html.erb
<div class="background">
  <div class="box">
    <h1>About</h1>
    <h4>Welcome to the BOS Bosham Oil Syndicate!</h4>
    <p>This website is for property owners in the Bosham area that require imported oil. Through the Bosham Oil Syndicate, administrated by Mrs Racheal Murphy, the website is tasked with providing the admin information on syndicate members key information, primarily their fuel cap and oil requirements. Once all oil requirements are collected, the administrator will assess various oil distributors to collect the necessary quantity of oil.</p>
    <br>
    <%= link_to "Back to the Home Page", root_path, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
  </div>
</div>

app/views/pages/contact.html.erb
<h2>Contacts:</h2>
<h3></h3>

app/views/pages/home.html.erb
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="components/_index.scss" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Website Homepage</title>
</head>
<div class="index">
  <div class="container">
    <h1>Welcome to the Bosham Oil Syndicate</h1>
    <h3>Please log in to access your account and view the BOS fuel</h3>
    <br>
    <div class="button">
      <%= link_to "About the site", about_path, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
    </div>
    <div class="button">
      <%= link_to "Admin Log In", admin_session_path, class: "nav-link" %>
    </div>
    <div class="nav-item">
        <%= link_to "User Log In", user_session_path, class: "nav-link" %>
    </div>

     <div class="container" style="margin-top: -4pc;">
                  <div class="row p-5 top-hero text-center justify-content-around">
                      <div class="col-md-3 col-sm-5">
                          <%= link_to "User", new_user_registration_path( status: { status:"user" }),class: "btn btn-block btn-pink btn-site p-4 text-uppercase cta home-button", style: "color:white"%>
                      </div>
                      <div class="col-md-3 col-sm-5">
                        <%= link_to "admin", new_admin_registration_path( status: { status:"admin" } ),class: "btn btn-block btn-pink btn-site p-4 text-uppercase cta home-button", style: "color:white" %>
                      </div>
                  </div>
              </div>

    <%# <br> %>
    <%# <div class="button"> %>
      <%# <%= link_to "Contacts list", contact_path, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
    <%# </div> %>
    <%# <br> %>
    <%# <div class="button1"> %>
      <%#= link_to "Become a new Syndicator", syndicator_new_path, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
    <%# </div> %>
    <%# <br> %>
    <%# <div class="button1"> %>
      <%# <%= link_to "Admin to add new company", company_new_path, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
    <%# </div> %>
    <br>
  </div>
</div>

app/views/pages/primary.html.erb
<div class="primary">
  <h2 class="Title">Welcome Syndicator!</h2>
  <h5>This is the Bosham Oil Syndicate *BOS*. Please select the button below and go to your syndicate form. Once you have completed the form, you will be taken to the the Meeting Room.</h5>
  <h5>The 'Meeting Room' will be accessible 24/7 and is strictly for syndicators to review company information displayed via the sites admin and presented beside the *future* comment board.</h5>
  <h5>As updates are made to this site, key parts are likely to change, including a reset of the comment table every 24 hours and more interactive features.</h5>
  <%= link_to "Fill in Syndicator form", information_forms_url, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
</div>

app/views/pages/user.html.erb
<h5>hi</h5>