config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  root to: "pages#home"

  resources :dashboard_form, except: %i[index]
  get '/dashboard_forms', to: 'dashboard_forms#index', as: :form_for_admin

  devise_for :admins
    resources :dashboard_forms
  devise_for :users, controllers: { registrations: "users/registrations" }
    resources :information_forms


  get "about", to: "pages#about", as: :about
  get "information_form", to: "information_form#index", as: :form_for_user
  get 'users' => 'users#primary', as: :user_root
  get 'admins' => 'admin#primary', as: :admin_root


end

app/controllers/dashboard_form_controller.rb
class DashboardFormController < ApplicationController
  before_action :set_information_form, only: %i[ show edit update destroy ]

  # GET /information_forms or /information_forms.json
  def index
    @dashboard_form = DashboardForm.all
  end

  # GET /information_forms/1 or /information_forms/1.json
  def show
  end

  # GET /information_forms/new
  def new
    @dashboard_form = DashboardForm.new
  end

  # GET /information_forms/1/edit
  def edit
  end

  # POST /information_forms or /information_forms.json
  def create
    @dashboard_form = DashboardForm.new(dashboard_form_params)

    respond_to do |format|
      if @information_form.save
        format.html { redirect_to dashboard_form_url(@dashboard_form), notice: "Company File was successfully created." }
        format.json { render :show, status: :created, location: @information_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dashboard_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /information_forms/1 or /information_forms/1.json
  def update
    respond_to do |format|
      if @dashboard_form.update(dashboard_form_params)
        format.html { redirect_to dashboard_form_url(@dashboard_form), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @information_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dashboard_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information_forms/1 or /information_forms/1.json
  def destroy
    @dashboard_form.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_form_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard_form
      @dashboard_form = DashboardForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def information_form_params
      params.require(:dashboard_form).permit(:company_name, :address, :pounds_per_litre, :comment, :rating)
    end
end

app/controllers/dashboard_forms_controller.rb
class DashboardFormsController < ApplicationController
  before_action :set_dashboard_forms, only: %i[ show new edit update destroy ]

  # GET /dashboard_forms or /dashboard_forms.json
  def index
    @dashboard_forms = DashboardForm.all
  end

  # GET /dashboard_forms/1 or /dashboard_forms/1.json
  def show
    @fuel_needed = @fuel_needed.all
  end

  # GET /dashboard_forms/new
  def new
    @dashboard_form = DashboardForm.new
  end

  # GET /dashboard_forms/1/edit
  def edit
  end

  # POST /dashboard_forms or /dashboard_forms.json
  def create
    @dashboard_form = DashboardForm.new(dashboard_form_params)

    respond_to do |format|
      if @dashboard_form.save
        format.html { redirect_to dashboard_form_url(@dashboard_form), notice: "Dashboard form was successfully created." }
        format.json { render :show, status: :created, location: @dashboard_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dashboard_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboard_forms/1 or /dashboard_forms/1.json
  def update
    respond_to do |format|
      if @dashboard_form.update(dashboard_form_params)
        format.html { redirect_to dashboard_forms_url(@dashboard_form), notice: "Dashboard form was successfully updated." }
        format.json { render :show, status: :ok, location: @dashboard_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dashboard_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboard_forms/1 or /dashboard_forms/1.json
  def destroy
    @dashboard_form.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_forms_url, notice: "Dashboard form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard_forms
      # @dashboard_forms = DashboardForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dashboard_form_params
      params.require(:dashboard_form).permit(:company_name, :address, :pounds_per_litre, :comment, :rating)
    end
end

app/views/dashboard_forms/_dashboard_form.html.erb
<div id="<%= dom_id dashboard_form %>">
  <p>
    <strong>Company name:</strong>
    <%= dashboard_form.company_name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= dashboard_form.address %>
  </p>

  <p>
    <strong>Pounds per litre:</strong>
    <%= dashboard_form.pounds_per_litre %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= dashboard_form.comment %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= dashboard_form.rating %>
  </p>

</div>

app/views/dashboard_forms/_form.html.erb
<%= simple_form_for(@dashboard_form) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :company_name %>
    <%= f.input :address %>
    <%= f.input :pounds_per_litre %>
    <%= f.input :comment %>
    <%= f.input :rating %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dashboard_forms/edit.html.erb
<h1>Editing dashboard form</h1>

<%= render "form", dashboard_form: @dashboard_form %>

<br>

<div>
  <%= link_to "Show this company", @dashboard_form %> |
  <%= link_to "Back to company list", dashboard_forms_path %>
</div>

app/views/dashboard_forms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dashboard forms</h1>

<div id="dashboard_forms">
  <% @dashboard_form.each do |dashboard_form| %>
    <%= render dashboard_form %>
    <p>
      <%= link_to "Show this company", dashboard_form %>
    </p>
  <% end %>
</div>

<%= link_to "New company", new_dashboard_form_path %>
<%= link_to "Back to Admin Page", admin_session_url, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>

app/views/dashboard_forms/new.html.erb
<h1>New dashboard form</h1>

<%= render "form", dashboard_form: @dashboard_form %>

<br>

<div>
  <%= link_to "Back to company list", dashboard_forms_path %>
</div>

app/views/dashboard_forms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dashboard_form %>

<div>
  <%= link_to "Edit this company", edit_dashboard_form_path(@dashboard_form) %> |
  <%= link_to "Back to company list", dashboard_forms_path %>

  <%= button_to "Destroy this company file", @dashboard_form, method: :delete %>
</div>